version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/app/dist

  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth_db
    environment:
      MONGO_URL: mongodb://auth_db:27017
      JWT_SECRET: supersecret

  auth_db:
    container_name: auth_db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db

  message:
    container_name: message
    build:
      context: ./message
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - message_db
    environment:
      MONGO_URL: mongodb://message_db:27017
      NODE_ENV: production
    restart: unless-stopped

  message_db:
    container_name: message_db
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - message_data:/data/db

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - frontend:/usr/share/nginx/html
    depends_on:
      - frontend
      - message
      - auth

volumes:
  frontend:
  auth_data:
  message_data:
