version: "3.8"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - portfolio
    restart: unless-stopped
    ports:
      - "80:80"
    args:
      VITE_REACT_APP_BACKEND_URL: "193.165.29.194:3001"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - portfolio
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
